In [30]:
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [31]:
directory = "E:/instagram_dataset_raws/Instagram influencer dataset/"

### Load influencers

In [32]:
import pandas as pd
import os

influencers = pd.read_csv(
    os.path.join(directory, "influencers.txt"),
    sep="\t",   # change to "," if needed
    header=None,
    names=["username", "category", "followers", "followees", "num_posts"]
)

influencers.head()

,username,category,followers,followees,num_posts
0,Username,Category,#Followers,#Followees,#Posts
1,==============================================...,NaN,NaN,NaN,NaN
2,makeupbynvs,beauty,1432,1089,363
3,jaquelinevandoski,beauty,137600,548,569
4,anisaartistry,beauty,64644,289,391

### Count how many influencers per category

In [33]:
influencers["category"].value_counts()

category
fashion        11911
other           5720
travel          4210
family          4070
food            3565
beauty          1542
interior        1195
fitness         1133
pet              587
Category           1
fasion             1
fashion 0.5        1
Name: count, dtype: int64

There are 33,935 influencers in 9 categories, and each influencer has 300 posts. Each post has metadata and image files. 
To reduce the data being used, I will do a random sample of 50 influencers from each category, and all 300 of their posts, resulting in 9x50x300=100k+ posts.
If this helps the performance, then I may increase the number of users used from the dataset.

OR, we do 300 influencers from each category, 50 of each of their posts. so 9*300*50 is 100k+

In [34]:
exclude_categories = [
    "Category",
    "fasion",
    "fashion 0.5"
]

In [35]:
N = 300

filtered_influencers = influencers[
    (~influencers["category"].isin(exclude_categories)) &
    (influencers["category"].notna())
].reset_index(drop=True)

sampled_influencers = (
    filtered_influencers
    .groupby("category", group_keys=False)
    .apply(lambda x: x.sample(
        n=min(len(x), N),  # avoid errors if category is small
        random_state=42
    ))
    .reset_index(drop=True)
)

C:\Users\sugar\AppData\Local\Temp\ipykernel_95136\769756936.py:11: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: x.sample(

In [36]:
sampled_influencers["category"].value_counts()

category
beauty      300
family      300
fashion     300
fitness     300
food        300
interior    300
other       300
pet         300
travel      300
Name: count, dtype: int64

### Build a set of valid usernames

In [37]:
valid_usernames = set(sampled_influencers["username"])

In [38]:
print(len(valid_usernames))

2700

### Build mapping from metadata JSON to image files, filtering for only selected influencers

In [39]:
mapping_file = os.path.join(directory, "JSON-Image_files_mapping.txt")

In [40]:
# Search for exact username and post id
target_username = "maddchadd"
target_post_id = "814722363889295440"

with open(mapping_file, "r", encoding="utf-8") as f:
    for i, line in enumerate(f, 1):
        if (
            line.startswith(target_username + "\t")
            and target_post_id in line
        ):
            print(f"Found at line {i}:")
            print(line)
            break
    else:
        print("No matching line found")

Found at line 5472020:
maddchadd	814722363889295440.info	['814722363889295440.jpg']

In [41]:
from collections import defaultdict
import ast

# json_to_images = defaultdict(list)
user_posts = defaultdict(list)

with open(mapping_file, "r", encoding="utf-8") as f:
    for i, line in enumerate(f, 1):
        parts = line.rstrip().split("\t")

        if len(parts) != 3:
            continue

        username, info_file, image_list_str = parts
        username = username.strip().lower()  # normalize
        if username not in valid_usernames:
            # print(f"excluded:{username}")
            continue

        # Safely parse "['img1.jpg', 'img2.jpg']"
        image_files = ast.literal_eval(image_list_str)

        # store raw post info temporarily
        user_posts[username].append((info_file, image_files))

        # # prepend username to filenames
        # full_info_file = f"{username}-{info_file}"
        # full_image_files = [f"{username}-{img}" for img in image_files]

        # json_to_images[full_info_file].extend(full_image_files)
        # json_to_images[full_info_file] = list(set(json_to_images[full_info_file]))


        if i % 100_000 == 0:
            print(f"Processed {i:,} lines")

Processed 900,000 lines
Processed 2,100,000 lines
Processed 3,100,000 lines
Processed 5,200,000 lines
Processed 5,300,000 lines
Processed 6,000,000 lines
Processed 8,200,000 lines
Processed 8,300,000 lines
Processed 8,400,000 lines
Processed 8,700,000 lines
Processed 9,000,000 lines

Randomly select 50 posts per user

In [42]:
import random

json_to_images = defaultdict(list)

for username, posts in user_posts.items():
    sampled_posts = random.sample(posts, min(50, len(posts)))

    for info_file, image_files in sampled_posts:
        full_info_file = f"{username}-{info_file}"
        full_image_files = [f"{username}-{img}" for img in image_files]

        json_to_images[full_info_file].extend(full_image_files)
        json_to_images[full_info_file] = list(set(json_to_images[full_info_file]))

### Verify mapping completion

In [43]:
print("Valid usernames:", len(valid_usernames))
print("Posts kept:", len(json_to_images))
print("Total images:", sum(len(v) for v in json_to_images.values()))

Valid usernames: 2700
Posts kept: 134875
Total images: 171415

In [44]:
len(json_to_images)

134875

In [45]:
next(iter(json_to_images.items()))

('0paline-2014775930511050102.info',
 ['0paline-2014775925838489241.jpg',
  '0paline-2014775925821784458.jpg',
  '0paline-2014775925838478446.jpg',
  '0paline-2014775925813521200.jpg',
  '0paline-2014775925846950483.jpg'])

Check images count

In [46]:
from collections import Counter

image_count_dist = Counter(len(v) for v in json_to_images.values())
image_count_dist

Counter({1: 120436,
         2: 6402,
         3: 3212,
         4: 1676,
         5: 997,
         6: 643,
         10: 532,
         7: 403,
         8: 322,
         9: 251,
         16: 1})

In [47]:
bad_post = [k for k, v in json_to_images.items() if len(v) > 10][0]
bad_post

'alligoldenphotography-1907860073340206212.info'

In [48]:
images = json_to_images[bad_post]

print("Number of images:", len(images))
for img in images:
    print(img)

Number of images: 16
alligoldenphotography-1907859653010782141.jpg
alligoldenphotography-1907858717915902378.jpg
alligoldenphotography-1907859662582177727.jpg
alligoldenphotography-1907859654092797370.jpg
alligoldenphotography-1907858710181681820.jpg
alligoldenphotography-1907858712782109408.jpg
alligoldenphotography-1907858710651276251.jpg
alligoldenphotography-1907859661391003119.jpg
alligoldenphotography-1907858714057241080.jpg
alligoldenphotography-1907859667766450920.jpg
alligoldenphotography-1907858713260092423.jpg
alligoldenphotography-1907859654839524992.jpg
alligoldenphotography-1907859670006171284.jpg
alligoldenphotography-1907859661852471508.jpg
alligoldenphotography-1907858718293272575.jpg
alligoldenphotography-1907858711389510592.jpg

### Whitelist of JSON filenames

In [49]:
json_files_to_load = set(json_to_images.keys())
len(json_files_to_load)

134875

In [50]:
next(iter(json_files_to_load))

'thelittlefarmhands-1982759599238074396.info'

### Functions to extract image paths and find files

In [51]:
def find_all_images(folder_path):
    return sorted([
        os.path.join(folder_path, f)
        for f in os.listdir(folder_path)
        if f.lower().endswith((".jpg", ".jpeg", ".png"))
    ])

In [52]:
def find_file_by_ext(folder_path, extensions):
    """
    Returns the first file in folder_path matching any extension in extensions
    """
    for f in os.listdir(folder_path):
        if f.lower().endswith(extensions):
            return os.path.join(folder_path, f)
    return None

### Quick view of metadata contents

In [53]:
import json, gzip, lzma

def load_metadata(path):
    if path.endswith(".gz"):
        with gzip.open(path, "rt", encoding="utf-8") as f:
            return json.load(f)
    elif path.endswith(".xz"):
        with lzma.open(path, "rt", encoding="utf-8") as f:
            return json.load(f)

# Test loading of metadata with 1 sample
json_dir = os.path.join(directory, "Post_metadata/posts_info/info")
# json_file = next(iter(json_files_to_load))
json_files_to_load_list = list(json_files_to_load)
json_file = json_files_to_load_list[100] # random entry

meta_path = os.path.join(json_dir, json_file)
# meta = load_metadata(meta_path)
with open(meta_path, "r", encoding="utf-8") as f:
        meta = json.load(f)
print(meta.keys())
# print(meta['node'].keys())
for k, v in meta.items(): #['node'].items():
    print("KEY:", k)
    print("VALUE:", v)
    print("-" * 40)

dict_keys(['gating_info', 'viewer_can_reshare', 'display_resources', 'viewer_in_photo_of_you', 'viewer_has_saved_to_collection', 'viewer_has_saved', 'owner', 'viewer_has_liked', 'id', 'edge_media_preview_like', 'edge_media_to_tagged_user', 'dimensions', 'fact_check_information', '__typename', 'location', 'shortcode', 'is_ad', 'caption_is_edited', 'edge_media_to_parent_comment', 'media_preview', 'taken_at_timestamp', 'edge_media_to_caption', 'tracking_token', 'has_ranked_comments', 'display_url', 'edge_web_media_to_related_media', 'edge_media_preview_comment', 'comments_disabled', 'edge_media_to_sponsor_user', 'accessibility_caption', 'is_video'])
KEY: gating_info
VALUE: None
----------------------------------------
KEY: viewer_can_reshare
VALUE: True
----------------------------------------
KEY: display_resources
VALUE: [{'src': 'https://scontent-lax3-1.cdninstagram.com/vp/9678824f22caf22e47c9e046ca690091/5E06792E/t51.2885-15/sh0.08/e35/s640x640/21227712_1888184171422856_5803303915650809856_n.jpg?_nc_ht=scontent-lax3-1.cdninstagram.com&_nc_cat=108', 'config_width': 640, 'config_height': 536}, {'src': 'https://scontent-lax3-1.cdninstagram.com/vp/ba82ad762268a684ae05b6cb41dc0bb6/5DF1DCEA/t51.2885-15/sh0.08/e35/s750x750/21227712_1888184171422856_5803303915650809856_n.jpg?_nc_ht=scontent-lax3-1.cdninstagram.com&_nc_cat=108', 'config_width': 750, 'config_height': 629}, {'src': 'https://scontent-lax3-1.cdninstagram.com/vp/4602a0ce96c13fa64dfeb119a0f20559/5DF27594/t51.2885-15/e35/21227712_1888184171422856_5803303915650809856_n.jpg?_nc_ht=scontent-lax3-1.cdninstagram.com&_nc_cat=108', 'config_width': 1080, 'config_height': 906}]
----------------------------------------
KEY: viewer_in_photo_of_you
VALUE: False
----------------------------------------
KEY: viewer_has_saved_to_collection
VALUE: False
----------------------------------------
KEY: viewer_has_saved
VALUE: False
----------------------------------------
KEY: owner
VALUE: {'username': 'spyro_dog', 'is_unpublished': False, 'requested_by_viewer': False, 'followed_by_viewer': False, 'has_blocked_viewer': False, 'profile_pic_url': 'https://scontent-lax3-1.cdninstagram.com/vp/37899565aa262a760ece35d81e4d841f/5DFD6DF3/t51.2885-19/s150x150/37342981_291011814981959_6876080162283192320_n.jpg?_nc_ht=scontent-lax3-1.cdninstagram.com', 'full_name': 'Senior blind westie dog 🐾', 'blocked_by_viewer': False, 'is_verified': False, 'id': '1675959356', 'is_private': False}
----------------------------------------
KEY: viewer_has_liked
VALUE: False
----------------------------------------
KEY: id
VALUE: 1401153009472127823
----------------------------------------
KEY: edge_media_preview_like
VALUE: {'count': 1277, 'edges': []}
----------------------------------------
KEY: edge_media_to_tagged_user
VALUE: {'edges': [{'node': {'y': 0.52287996, 'x': 0.5940777, 'user': {'username': 'jas_perly', 'profile_pic_url': 'https://scontent-lax3-1.cdninstagram.com/vp/54a3c28bac32747af9486ff0ec0da69e/5DFCD63A/t51.2885-19/11032917_668014473325257_1540788515_a.jpg?_nc_ht=scontent-lax3-1.cdninstagram.com', 'is_verified': False, 'id': '301195703', 'full_name': 'solopatrizia'}}}]}
----------------------------------------
KEY: dimensions
VALUE: {'width': 1080, 'height': 906}
----------------------------------------
KEY: fact_check_information
VALUE: None
----------------------------------------
KEY: __typename
VALUE: GraphImage
----------------------------------------
KEY: location
VALUE: None
----------------------------------------
KEY: shortcode
VALUE: BNx5T0NjkNP
----------------------------------------
KEY: is_ad
VALUE: False
----------------------------------------
KEY: caption_is_edited
VALUE: False
----------------------------------------
KEY: edge_media_to_parent_comment
VALUE: {'count': 76, 'page_info': {'end_cursor': 'QVFEcTBpRF8xaF9XSHh1X3ZBRG5OQnYxNlc0VmtfYnVNREotNHd0SGFLQ0d5MTY4NUY3YWZCV0VEbzV1aW9MeHZ2c1ZHT2tCZUhjNEhuOFZubUlKN3FzUw==', 'has_next_page': True}, 'edges': [{'node': {'text': 'Happy birthday to Jasper', 'created_at': 1481282867, 'did_report_as_spam': False, 'edge_liked_by': {'count': 0}, 'owner': {'username': 'pupsonpar', 'profile_pic_url': 'https://scontent-lax3-1.cdninstagram.com/vp/65756cb72a5bc9dc18e8c0d62f38e2c9/5E009826/t51.2885-19/s150x150/12797968_242326606105674_2074796180_a.jpg?_nc_ht=scontent-lax3-1.cdninstagram.com', 'is_verified': False, 'id': '729598945'}, 'viewer_has_liked': False, 'edge_threaded_comments': {'count': 0, 'page_info': {'end_cursor': None, 'has_next_page': False}, 'edges': []}, 'id': '17845239487154949'}}, {'node': {'text': 'What a great picture!!! 😍', 'created_at': 1481287921, 'did_report_as_spam': False, 'edge_liked_by': {'count': 0}, 'owner': {'username': 'coopiethewestie', 'profile_pic_url': 'https://scontent-lax3-1.cdninstagram.com/vp/b225af28a2ba36e786ba510efcb14d84/5E0CCBCD/t51.2885-19/s150x150/19985544_1472873479459555_7477790834046271488_a.jpg?_nc_ht=scontent-lax3-1.cdninstagram.com', 'is_verified': False, 'id': '1648999922'}, 'viewer_has_liked': False, 'edge_threaded_comments': {'count': 0, 'page_info': {'end_cursor': None, 'has_next_page': False}, 'edges': []}, 'id': '17860797976065651'}}, {'node': {'text': 'Se te ve agotado después de tanta pawty 😎', 'created_at': 1481289648, 'did_report_as_spam': False, 'edge_liked_by': {'count': 0}, 'owner': {'username': 'golfothewesty', 'profile_pic_url': 'https://scontent-lax3-1.cdninstagram.com/vp/dcc8c251d197bfdc3e3329fda93aaad2/5E11BA6B/t51.2885-19/s150x150/12346067_499582583554486_327104536_a.jpg?_nc_ht=scontent-lax3-1.cdninstagram.com', 'is_verified': False, 'id': '1549069841'}, 'viewer_has_liked': False, 'edge_threaded_comments': {'count': 0, 'page_info': {'end_cursor': None, 'has_next_page': False}, 'edges': []}, 'id': '17858228140077193'}}, {'node': {'text': '@madelynkk', 'created_at': 1481293352, 'did_report_as_spam': False, 'edge_liked_by': {'count': 0}, 'owner': {'username': 'surgekk', 'profile_pic_url': 'https://scontent-lax3-1.cdninstagram.com/vp/5dd6578d01e21435a51892517ffbff24/5E18589A/t51.2885-19/s150x150/47583767_2165693386980096_6860676163291840512_n.jpg?_nc_ht=scontent-lax3-1.cdninstagram.com', 'is_verified': False, 'id': '275316854'}, 'viewer_has_liked': False, 'edge_threaded_comments': {'count': 0, 'page_info': {'end_cursor': None, 'has_next_page': False}, 'edges': []}, 'id': '17867348761039729'}}, {'node': {'text': '🐶❤❤❤❤', 'created_at': 1481303847, 'did_report_as_spam': False, 'edge_liked_by': {'count': 0}, 'owner': {'username': 'osyakama', 'profile_pic_url': 'https://scontent-lax3-1.cdninstagram.com/vp/1d133b3f3098c6287e5812c7ffa0184e/5E0ECAC2/t51.2885-19/s150x150/67455360_1308581795990479_2733782873298436096_n.jpg?_nc_ht=scontent-lax3-1.cdninstagram.com', 'is_verified': False, 'id': '2361964750'}, 'viewer_has_liked': False, 'edge_threaded_comments': {'count': 0, 'page_info': {'end_cursor': None, 'has_next_page': False}, 'edges': []}, 'id': '17845282990174542'}}, {'node': {'text': 'Aww Spyro!! Happy birthday to Jasper!! 🎁🎉🎂', 'created_at': 1481316621, 'did_report_as_spam': False, 'edge_liked_by': {'count': 0}, 'owner': {'username': 'daisymaewestie', 'profile_pic_url': 'https://scontent-lax3-1.cdninstagram.com/vp/fadb01f8476150fd4586414a8ebf7b5e/5E0A0A83/t51.2885-19/s150x150/47191945_215322886035690_2115556025057673216_n.jpg?_nc_ht=scontent-lax3-1.cdninstagram.com', 'is_verified': False, 'id': '1560007219'}, 'viewer_has_liked': False, 'edge_threaded_comments': {'count': 0, 'page_info': {'end_cursor': None, 'has_next_page': False}, 'edges': []}, 'id': '17867561728044103'}}, {'node': {'text': '😄🎉💃🏻 Happy Birthday to Jasper!❤️', 'created_at': 1481323888, 'did_report_as_spam': False, 'edge_liked_by': {'count': 0}, 'owner': {'username': 'westies_boatsman_and_henry', 'profile_pic_url': 'https://scontent-lax3-1.cdninstagram.com/vp/040de22220294424db9a8fa04e1da7bf/5DF5B8D4/t51.2885-19/s150x150/66342889_871507846568610_5317192189875322880_n.jpg?_nc_ht=scontent-lax3-1.cdninstagram.com', 'is_verified': False, 'id': '2344233713'}, 'viewer_has_liked': False, 'edge_threaded_comments': {'count': 0, 'page_info': {'end_cursor': None, 'has_next_page': False}, 'edges': []}, 'id': '17856749053099983'}}, {'node': {'text': 'Happy Birthday, Jasper🎉✨😆✨🎊', 'created_at': 1481336797, 'did_report_as_spam': False, 'edge_liked_by': {'count': 0}, 'owner': {'username': 'miroansal', 'profile_pic_url': 'https://scontent-lax3-1.cdninstagram.com/vp/1f9f58002cd2766115f8b75726d9dcf6/5DF27743/t51.2885-19/11176431_1570998056519436_682819319_a.jpg?_nc_ht=scontent-lax3-1.cdninstagram.com', 'is_verified': False, 'id': '1998005185'}, 'viewer_has_liked': False, 'edge_threaded_comments': {'count': 0, 'page_info': {'end_cursor': None, 'has_next_page': False}, 'edges': []}, 'id': '17845303705168040'}}, {'node': {'text': 'Heh heh!! Sweet dreams, honey bun! ♡', 'created_at': 1481457687, 'did_report_as_spam': False, 'edge_liked_by': {'count': 0}, 'owner': {'username': 'shellsherree', 'profile_pic_url': 'https://scontent-lax3-1.cdninstagram.com/vp/20570b5d345e76be06a62d05a7af9db7/5E099887/t51.2885-19/s150x150/16110268_1857183751232100_7485721882000359424_a.jpg?_nc_ht=scontent-lax3-1.cdninstagram.com', 'is_verified': False, 'id': '604215009'}, 'viewer_has_liked': False, 'edge_threaded_comments': {'count': 0, 'page_info': {'end_cursor': None, 'has_next_page': False}, 'edges': []}, 'id': '17868097441050494'}}, {'node': {'text': 'Too cute ❤️❤️❤️', 'created_at': 1481592103, 'did_report_as_spam': False, 'edge_liked_by': {'count': 0}, 'owner': {'username': 'lizzie.bear', 'profile_pic_url': 'https://scontent-lax3-1.cdninstagram.com/vp/319948a0418ae82083316dfa5a9c2a11/5E0B7890/t51.2885-19/s150x150/67900894_2613742961980973_4782415542583558144_n.jpg?_nc_ht=scontent-lax3-1.cdninstagram.com', 'is_verified': False, 'id': '1242715225'}, 'viewer_has_liked': False, 'edge_threaded_comments': {'count': 0, 'page_info': {'end_cursor': None, 'has_next_page': False}, 'edges': []}, 'id': '17845190239188848'}}, {'node': {'text': 'Ad🍭rable!!', 'created_at': 1481599535, 'did_report_as_spam': False, 'edge_liked_by': {'count': 0}, 'owner': {'username': 'digsby_n_cinderella_the_chows', 'profile_pic_url': 'https://scontent-lax3-1.cdninstagram.com/vp/bb14dd62c21f982964e60fbab10007d2/5DF303F1/t51.2885-19/s150x150/31754682_615162358833796_7719991921132699648_n.jpg?_nc_ht=scontent-lax3-1.cdninstagram.com', 'is_verified': False, 'id': '1438882870'}, 'viewer_has_liked': False, 'edge_threaded_comments': {'count': 0, 'page_info': {'end_cursor': None, 'has_next_page': False}, 'edges': []}, 'id': '17845386883160621'}}, {'node': {'text': 'Love!❤️', 'created_at': 1481655202, 'did_report_as_spam': False, 'edge_liked_by': {'count': 0}, 'owner': {'username': 'violet_the_dapple_doxie', 'profile_pic_url': 'https://scontent-lax3-1.cdninstagram.com/vp/5906c58dc7d9442cfccd12f7f9b67532/5DF7B4B3/t51.2885-19/s150x150/15258834_1378262975517593_2486104904045690880_a.jpg?_nc_ht=scontent-lax3-1.cdninstagram.com', 'is_verified': False, 'id': '2121703864'}, 'viewer_has_liked': False, 'edge_threaded_comments': {'count': 0, 'page_info': {'end_cursor': None, 'has_next_page': False}, 'edges': []}, 'id': '17867588932053601'}}, {'node': {'text': '@digsby_n_cinderella_the_chows thank you sweetie 😘', 'created_at': 1481682073, 'did_report_as_spam': False, 'edge_liked_by': {'count': 0}, 'owner': {'username': 'spyro_dog', 'profile_pic_url': 'https://scontent-lax3-1.cdninstagram.com/vp/37899565aa262a760ece35d81e4d841f/5DFD6DF3/t51.2885-19/s150x150/37342981_291011814981959_6876080162283192320_n.jpg?_nc_ht=scontent-lax3-1.cdninstagram.com', 'is_verified': False, 'id': '1675959356'}, 'viewer_has_liked': False, 'edge_threaded_comments': {'count': 0, 'page_info': {'end_cursor': None, 'has_next_page': False}, 'edges': []}, 'id': '17845419559168779'}}, {'node': {'text': '@violet_the_dapple_doxie 😘💕😘💕', 'created_at': 1481682084, 'did_report_as_spam': False, 'edge_liked_by': {'count': 0}, 'owner': {'username': 'spyro_dog', 'profile_pic_url': 'https://scontent-lax3-1.cdninstagram.com/vp/37899565aa262a760ece35d81e4d841f/5DFD6DF3/t51.2885-19/s150x150/37342981_291011814981959_6876080162283192320_n.jpg?_nc_ht=scontent-lax3-1.cdninstagram.com', 'is_verified': False, 'id': '1675959356'}, 'viewer_has_liked': False, 'edge_threaded_comments': {'count': 0, 'page_info': {'end_cursor': None, 'has_next_page': False}, 'edges': []}, 'id': '17857125574107884'}}, {'node': {'text': '@lizzie.bear thank you 💓 💓 I party hard in my dreams', 'created_at': 1481682107, 'did_report_as_spam': False, 'edge_liked_by': {'count': 0}, 'owner': {'username': 'spyro_dog', 'profile_pic_url': 'https://scontent-lax3-1.cdninstagram.com/vp/37899565aa262a760ece35d81e4d841f/5DFD6DF3/t51.2885-19/s150x150/37342981_291011814981959_6876080162283192320_n.jpg?_nc_ht=scontent-lax3-1.cdninstagram.com', 'is_verified': False, 'id': '1675959356'}, 'viewer_has_liked': False, 'edge_threaded_comments': {'count': 0, 'page_info': {'end_cursor': None, 'has_next_page': False}, 'edges': []}, 'id': '17856361141121076'}}, {'node': {'text': '@shellsherree thank you darling 😘 😘 😘', 'created_at': 1481682120, 'did_report_as_spam': False, 'edge_liked_by': {'count': 0}, 'owner': {'username': 'spyro_dog', 'profile_pic_url': 'https://scontent-lax3-1.cdninstagram.com/vp/37899565aa262a760ece35d81e4d841f/5DFD6DF3/t51.2885-19/s150x150/37342981_291011814981959_6876080162283192320_n.jpg?_nc_ht=scontent-lax3-1.cdninstagram.com', 'is_verified': False, 'id': '1675959356'}, 'viewer_has_liked': False, 'edge_threaded_comments': {'count': 0, 'page_info': {'end_cursor': None, 'has_next_page': False}, 'edges': []}, 'id': '17867288485025473'}}, {'node': {'text': '@miroansal I think he had a fun time', 'created_at': 1481682144, 'did_report_as_spam': False, 'edge_liked_by': {'count': 0}, 'owner': {'username': 'spyro_dog', 'profile_pic_url': 'https://scontent-lax3-1.cdninstagram.com/vp/37899565aa262a760ece35d81e4d841f/5DFD6DF3/t51.2885-19/s150x150/37342981_291011814981959_6876080162283192320_n.jpg?_nc_ht=scontent-lax3-1.cdninstagram.com', 'is_verified': False, 'id': '1675959356'}, 'viewer_has_liked': False, 'edge_threaded_comments': {'count': 0, 'page_info': {'end_cursor': None, 'has_next_page': False}, 'edges': []}, 'id': '17867563909027982'}}, {'node': {'text': '@golfothewesty de más.... 😂 😂 😂', 'created_at': 1481682161, 'did_report_as_spam': False, 'edge_liked_by': {'count': 0}, 'owner': {'username': 'spyro_dog', 'profile_pic_url': 'https://scontent-lax3-1.cdninstagram.com/vp/37899565aa262a760ece35d81e4d841f/5DFD6DF3/t51.2885-19/s150x150/37342981_291011814981959_6876080162283192320_n.jpg?_nc_ht=scontent-lax3-1.cdninstagram.com', 'is_verified': False, 'id': '1675959356'}, 'viewer_has_liked': False, 'edge_threaded_comments': {'count': 0, 'page_info': {'end_cursor': None, 'has_next_page': False}, 'edges': []}, 'id': '17867764393057105'}}, {'node': {'text': '@emma_the_westie 🎉 🎊 🎉 🎊', 'created_at': 1481682174, 'did_report_as_spam': False, 'edge_liked_by': {'count': 0}, 'owner': {'username': 'spyro_dog', 'profile_pic_url': 'https://scontent-lax3-1.cdninstagram.com/vp/37899565aa262a760ece35d81e4d841f/5DFD6DF3/t51.2885-19/s150x150/37342981_291011814981959_6876080162283192320_n.jpg?_nc_ht=scontent-lax3-1.cdninstagram.com', 'is_verified': False, 'id': '1675959356'}, 'viewer_has_liked': False, 'edge_threaded_comments': {'count': 0, 'page_info': {'end_cursor': None, 'has_next_page': False}, 'edges': []}, 'id': '17867283946022801'}}, {'node': {'text': 'Awww! Sweet!', 'created_at': 1481692175, 'did_report_as_spam': False, 'edge_liked_by': {'count': 0}, 'owner': {'username': 'heart.px', 'profile_pic_url': 'https://scontent-lax3-1.cdninstagram.com/vp/507c8bee1bfbdaf6289e71937aec0435/5DF435FB/t51.2885-19/s150x150/51292045_2267194440274263_6878733137812127744_n.jpg?_nc_ht=scontent-lax3-1.cdninstagram.com', 'is_verified': False, 'id': '1150461739'}, 'viewer_has_liked': False, 'edge_threaded_comments': {'count': 0, 'page_info': {'end_cursor': None, 'has_next_page': False}, 'edges': []}, 'id': '17855553925093507'}}, {'node': {'text': 'Lovely 😍😍', 'created_at': 1481905498, 'did_report_as_spam': False, 'edge_liked_by': {'count': 0}, 'owner': {'username': 'karlsson_the_awesome_westie', 'profile_pic_url': 'https://scontent-lax3-1.cdninstagram.com/vp/a589981b1c422d2ee397e0bbb1f5e865/5DF2BAFA/t51.2885-19/s150x150/26066667_1411132998990632_1744301736345993216_n.jpg?_nc_ht=scontent-lax3-1.cdninstagram.com', 'is_verified': False, 'id': '578094693'}, 'viewer_has_liked': False, 'edge_threaded_comments': {'count': 0, 'page_info': {'end_cursor': None, 'has_next_page': False}, 'edges': []}, 'id': '17856962248112891'}}, {'node': {'text': '😂😂😍😘😍😘', 'created_at': 1482267637, 'did_report_as_spam': False, 'edge_liked_by': {'count': 0}, 'owner': {'username': 'shorkie_sofie_auntie_ethel', 'profile_pic_url': 'https://scontent-lax3-1.cdninstagram.com/vp/7893ace2fcb8fa67fa519e97f177dd3b/5DF550A7/t51.2885-19/s150x150/18723403_579564485500713_1287179871587401728_a.jpg?_nc_ht=scontent-lax3-1.cdninstagram.com', 'is_verified': False, 'id': '1338626606'}, 'viewer_has_liked': False, 'edge_threaded_comments': {'count': 0, 'page_info': {'end_cursor': None, 'has_next_page': False}, 'edges': []}, 'id': '17866965397020452'}}, {'node': {'text': "Adorable! ❤️ I don't know why, but I've missed a bunch of your posts. It makes mom sad because we love following you!!🐾😍🐾", 'created_at': 1484681195, 'did_report_as_spam': False, 'edge_liked_by': {'count': 0}, 'owner': {'username': 'zestywestie', 'profile_pic_url': 'https://scontent-lax3-1.cdninstagram.com/vp/d6d11d58ca8b0e80d1145e42ee2d2c4b/5E00D799/t51.2885-19/s150x150/12950307_258259584521623_292062402_a.jpg?_nc_ht=scontent-lax3-1.cdninstagram.com', 'is_verified': False, 'id': '2225663761'}, 'viewer_has_liked': False, 'edge_threaded_comments': {'count': 0, 'page_info': {'end_cursor': None, 'has_next_page': False}, 'edges': []}, 'id': '17858948296117844'}}, {'node': {'text': "@zestywestie don't worry my dear, we miss many posts too. We feel the love and send you lots of love back. 💕💓💕💓💕💓💕", 'created_at': 1484686118, 'did_report_as_spam': False, 'edge_liked_by': {'count': 0}, 'owner': {'username': 'spyro_dog', 'profile_pic_url': 'https://scontent-lax3-1.cdninstagram.com/vp/37899565aa262a760ece35d81e4d841f/5DFD6DF3/t51.2885-19/s150x150/37342981_291011814981959_6876080162283192320_n.jpg?_nc_ht=scontent-lax3-1.cdninstagram.com', 'is_verified': False, 'id': '1675959356'}, 'viewer_has_liked': False, 'edge_threaded_comments': {'count': 0, 'page_info': {'end_cursor': None, 'has_next_page': False}, 'edges': []}, 'id': '17847221080179234'}}]}
----------------------------------------
KEY: media_preview
VALUE: ACojvtnHHXtTo38xQw7/AM+4oRGfGBwBTFiNtkuyhT6nofr0pGlly+ZNg00g05sEY9aiib+E9uv+f88igiwyT5RuPNVfN9jVmdjjHuKqFhWbZcVc1njl8vbCQjFh8xGcDjPr+H9KkmAf5SAynggjIp8mSpCnDYOPrWFMt3KdrBgoHYDn8utaN2CMOfql6vUveUCRGmQI8EAdD7HPp/KpTbnOc46/iD2qnpvmxswkDBSMgkd//wBVabsMZzgCmtiJKzte9uxXZRnmk8lfQfkKiEol+5kj1waftb3pCLmaQ0UVQhc00k0UUANJNNzRRQB//9k=
----------------------------------------
KEY: taken_at_timestamp
VALUE: 1481250476
----------------------------------------
KEY: edge_media_to_caption
VALUE: {'edges': [{'node': {'text': 'Party animals... 🎉 \nbuon compleanno Jasper! .\n#westie'}}]}
----------------------------------------
KEY: tracking_token
VALUE: eyJ2ZXJzaW9uIjo1LCJwYXlsb2FkIjp7ImlzX2FuYWx5dGljc190cmFja2VkIjp0cnVlLCJ1dWlkIjoiOWNkYzU3ZTc3MGQyNDFlNGExMjQ4ZWFhMmExMTM5NTkxNDAxMTUzMDA5NDcyMTI3ODIzIn0sInNpZ25hdHVyZSI6IiJ9
----------------------------------------
KEY: has_ranked_comments
VALUE: False
----------------------------------------
KEY: display_url
VALUE: https://scontent-lax3-1.cdninstagram.com/vp/4602a0ce96c13fa64dfeb119a0f20559/5DF27594/t51.2885-15/e35/21227712_1888184171422856_5803303915650809856_n.jpg?_nc_ht=scontent-lax3-1.cdninstagram.com&_nc_cat=108
----------------------------------------
KEY: edge_web_media_to_related_media
VALUE: {'edges': []}
----------------------------------------

### Extract post metadata from limited influencers

In [54]:
import json
import os
from pathlib import Path
from datetime import datetime, timezone
from tqdm import tqdm
from langdetect import detect, LangDetectException


records = []
bad_json_count = 0

json_dir = os.path.join(directory, "Post_metadata/posts_info/info")
image_dir = os.path.join(directory, "Post_images/posts_image/image")

# order and find total number
json_files_to_load = sorted(json_to_images.keys())
total_files = len(json_files_to_load)

# loop with progress 
for json_file in tqdm(json_files_to_load, total=total_files, desc="Processing posts"):
    json_path = os.path.join(json_dir, json_file)
    # json_path = str(Path(json_path).as_posix()) # normalise the path to /
    # if not os.path.exists(json_path):
    #     # print(json_path)
    #     continue

    try:
        with open(json_path, "r", encoding="utf-8") as f:
            metadata = json.load(f)
    except (json.JSONDecodeError, OSError, UnicodeDecodeError):
        bad_json_count += 1
        continue

    # ====================
    # JSON extraction
    # ====================

    # --- Extract metadata from nested JSON ---
    # node = metadata.get('node', {})

    # --- Caption ---
    edges = metadata.get("edge_media_to_caption", {}).get("edges", [])
    if not edges:
        continue

    caption = edges[0].get("node", {}).get("text", "").strip()
    if not caption:
        continue

    # --- Language filter ---
    try:
        if detect(caption) != "en": # keep only english captions
            continue
    except LangDetectException:
        continue

    # === Owner metrics ===
    # followers = metadata.get("owner", {}).get("edge_followed_by", {}).get("count", 0) #### DONT HAVE
    # following = metadata.get("owner", {}).get("edge_follow", {}).get("count", 0) #### DONT HAVE, in influencers.txt
    owner = metadata.get("owner", {})
    user_id = owner.get("id", None)#.get("count", 0)
    username = owner.get("username", None)

    # === Post metrics ===
    # Timestamp (convert from UNIX epoch to readable)
    ts = metadata.get('taken_at_timestamp', None)
    if ts:
        publish_timestamp = datetime.fromtimestamp(ts, tz=timezone.utc).strftime('%Y-%m-%d %H:%M:%S')
    else:
        publish_timestamp = ''

    # Location
    has_location = 1 if metadata.get("location") else 0

    # # Flag carousel posts (> 1 image)
    # sidecar = metadata.get("edge_sidecar_to_children") #### DONT HAVE

    # is_carousel = (
    #     1 if sidecar and len(sidecar.get("edges", [])) > 0 else 0
    # )

    # # Get number of images in post
    # if sidecar and "edges" in sidecar:
    #     num_images = len(sidecar["edges"])
    # else:
    #     num_images = 1  # single-image post

    # Flag sponsored content
    sponsor_edge = metadata.get("edge_media_to_sponsor_user")

    is_sponsored = (
        1 if sponsor_edge and len(sponsor_edge.get("edges", [])) > 0 else 0
    )

    # === Engagement-related ===
    # likes = metadata.get("edge_media_preview_like", {}).get("count", 0)
    # comments = metadata.get("edge_media_preview_comment", {}).get("count", 0) ### NO 'TO_COMMENT', HAVE 'PREVIEW_COMMENT'
    preview_like = metadata.get("edge_media_preview_like", {})
    preview_comment = metadata.get("edge_media_preview_comment", {})

    likes = preview_like.get("count", 0)
    comments = preview_comment.get("count", 0)

    # Calculate engagement rate
    # engagement_rate = (likes + comments) / max(followers, 1) # avoid division by 0

    

    # --- Find Image / Video file ---
    # Filter out video posts for this project
    if metadata.get("is_video"):
        continue  # skip video posts

    # Find number of image files for post
    image_list = json_to_images.get(json_file, [])
    # Extract all images, save local relative path in list
    image_path = [
            os.path.join(image_dir, img)
            for img in image_list
        ]
    # images = find_all_images(image_dir)
    # images[0] if images else None

    
    # Flag carousel posts (>1 image)
    is_carousel = 1 if len(image_list) > 1 else 0
    # Count number of images in post
    num_images = len(image_list)

    # if not image_list:
    #     continue

    if image_path is None:
        continue  # skip posts without images

    # ===============================
    records.append({
        # Owner metrics
        "user_id": user_id,
        "username": username,
        # "followers": followers, # in influencers.txt
        # "following": following, # in influencers.txt
        # Post metrics
        "publish_timestamp": publish_timestamp,
        "has_location": has_location,
        "is_carousel": is_carousel,
        "num_images": num_images,
        "is_sponsored": is_sponsored,
        "image_path": image_path,
        "caption": caption,
        # Engagement-related
        "likes": likes,
        "comments": comments,
        # "engagement_rate": engagement_rate   # calculate later
    })

    # record = {
    #     "username": data.get("username"),
    #     "post_id": data.get("id"),
    #     "caption": data.get("caption"),
    #     "num_likes": data.get("likes"),
    #     "num_comments": data.get("comments"),
    #     "timestamp": data.get("timestamp"),
    #     "is_sponsored": data.get("sponsored", False),
    #     "image_paths": [
    #         os.path.join(image_dir, img)
    #         for img in json_to_images[json_file]
    #     ],
    #     "num_images": len(json_to_images[json_file])
    # }

    # records.append(record)
print("Bad JSON files skipped:", bad_json_count)

Processing posts: 100%|██████████| 134875/134875 [1:41:59<00:00, 22.04it/s]

Bad JSON files skipped: 6239

### Create post-level dataframe

In [55]:
df_posts = pd.DataFrame(records)

df_posts.head()

,user_id,username,publish_timestamp,has_location,is_carousel,num_images,is_sponsored,image_path,caption,likes,comments
0,237173390,15minbeauty,2015-06-18 15:34:41,0,0,1,0,[E:/instagram_dataset_raws/Instagram influence...,#ad This summer I'm all about keeping my hair ...,39,4
1,237173390,15minbeauty,2015-06-22 12:37:40,0,0,1,0,[E:/instagram_dataset_raws/Instagram influence...,Trying out a ton of great new products right n...,98,0
2,237173390,15minbeauty,2015-07-06 15:33:50,0,0,1,0,[E:/instagram_dataset_raws/Instagram influence...,I spend a LOT of time and effort to keep my ha...,34,4
3,237173390,15minbeauty,2015-07-29 18:57:55,0,0,1,0,[E:/instagram_dataset_raws/Instagram influence...,"I'm not usually a shadow stick girl, they neve...",31,0
4,237173390,15minbeauty,2015-09-05 17:01:50,0,0,1,0,[E:/instagram_dataset_raws/Instagram influence...,#ad It's time to get ready for fall manicures ...,35,0

In [56]:
# Verify df_posts exists
df_posts.shape
# df_posts["num_images"].describe()
# df_posts["caption"].isna().mean()

(100432, 11)

### Merge influencer-level info (followers, followees) on username

In [57]:
df_posts_influencers = df_posts.merge(
    influencers[["username", "followers", "followees"]],
    on="username",
    how="left"
)

### Save dataframes as pickle

In [58]:
df_posts.to_pickle("df_posts_filtered.pkl")

In [59]:
df_posts_influencers.to_pickle("df_posts_influencers.pkl")